// Generated by scripts/generate-library-preview.cjs.
import {Image} from 'react-native';
export const galleryArtwork = [Image.resolveAssetSource(require('./night-library-reading.jpg')), Image.resolveAssetSource(require('./night-library-room.jpg'))];
