// Generated by scripts/generate-library-preview.cjs.
import image0 from './night-library-reading.jpg';
import image1 from './night-library-room.jpg';
export const galleryArtwork = [{uri: image0, width: 1080, height: 720}, {uri: image1, width: 1080, height: 720}] as const;
